version: '3.3'
services:
  practice_backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000

    volumes:
      - /practice_backend/node_modules
      - ./:/practice_backend

  redis-server:
    image: redis:latest
    ports:
      - 6379:6379
